# Generated by Django 3.1.1 on 2020-09-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('coursecover', models.CharField(max_length=255)),
                ('courseinfo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Course',
                'ordering': ('coursename',),
            },
        ),
    ]
