# Generated by Django 3.1.1 on 2020-09-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='PythonCourses',
        ),
        migrations.AlterModelOptions(
            name='pythoncourses',
            options={'ordering': ('coursename',), 'verbose_name_plural': 'Python Courses'},
        ),
    ]
