# Generated by Django 3.1.1 on 2020-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0002_auto_20200924_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncourses',
            name='courseinfo',
            field=models.TextField(blank=True),
        ),
    ]
