# Generated by Django 3.1.1 on 2020-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0003_auto_20200924_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythoncourses',
            old_name='courseinfo',
            new_name='courseinfo1',
        ),
        migrations.AddField(
            model_name='pythoncourses',
            name='courseinfo2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pythoncourses',
            name='courseinfo3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pythoncourses',
            name='courseinfo4',
            field=models.TextField(blank=True),
        ),
    ]
