# Generated by Django 3.1.1 on 2020-09-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0004_auto_20200924_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pythoncourses',
            options={'verbose_name_plural': 'Python Courses'},
        ),
        migrations.AddField(
            model_name='pythoncourses',
            name='courseinfo5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pythoncourses',
            name='courseinfo6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pythoncourses',
            name='courseinfo7',
            field=models.TextField(blank=True),
        ),
    ]
