# Generated by Django 3.1.1 on 2020-09-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0005_auto_20200924_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncourses',
            name='courseinfo5',
        ),
        migrations.RemoveField(
            model_name='pythoncourses',
            name='courseinfo6',
        ),
        migrations.RemoveField(
            model_name='pythoncourses',
            name='courseinfo7',
        ),
    ]
