# Generated by Django 3.1.1 on 2020-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0007_pythoncourses_coursenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncourses',
            name='coursenumber',
            field=models.IntegerField(),
        ),
    ]
