# Generated by Django 3.1.1 on 2020-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0009_auto_20200924_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncourses',
            name='coursetarget',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
