# Generated by Django 3.1.1 on 2020-09-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0010_pythoncourses_coursetarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncourses',
            name='coursecover',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
