# Generated by Django 3.1.1 on 2020-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0011_auto_20200924_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncourses',
            name='coursetarget',
            field=models.TextField(blank=True),
        ),
    ]
