# Generated by Django 3.1.1 on 2020-09-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0012_auto_20200924_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncourses',
            name='coursetarget',
        ),
    ]
