# Generated by Django 3.1.1 on 2020-09-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0013_remove_pythoncourses_coursetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.IntegerField()),
                ('coursename', models.CharField(max_length=255)),
                ('coursecover', models.CharField(blank=True, max_length=255)),
                ('courseinfo1', models.TextField(blank=True)),
                ('courseinfo2', models.TextField(blank=True)),
                ('courseinfo3', models.TextField(blank=True)),
                ('courseinfo4', models.TextField(blank=True)),
                ('courseinfo5', models.TextField(blank=True)),
                ('courseinfo6', models.TextField(blank=True)),
                ('courseinfo7', models.TextField(blank=True)),
                ('courseinfo8', models.TextField(blank=True)),
                ('courseinfo9', models.TextField(blank=True)),
                ('courseinfo10', models.TextField(blank=True)),
                ('courseinfo11', models.TextField(blank=True)),
                ('courseinfo12', models.TextField(blank=True)),
                ('courseinfo13', models.TextField(blank=True)),
                ('courseinfo14', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Python Linux',
            },
        ),
        migrations.DeleteModel(
            name='PythonCourses',
        ),
    ]
