# Generated by Django 3.1.1 on 2020-09-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0014_auto_20200925_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pythoncourse',
            options={'verbose_name_plural': 'Python Course'},
        ),
    ]
