# Generated by Django 3.1.1 on 2020-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0016_auto_20200925_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncourse',
            name='courseoverdet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pythoncourse',
            name='courseovertit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pythoncourse',
            name='coursereqdet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pythoncourse',
            name='coursereqtit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
