# Generated by Django 3.1.1 on 2020-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactcatcompany', '0018_auto_20200926_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonCourseJPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.IntegerField()),
                ('coursename', models.CharField(max_length=255)),
                ('courseovertit', models.CharField(max_length=255, null=True)),
                ('courseoverdet', models.TextField(blank=True)),
                ('coursereqtit', models.CharField(max_length=255, null=True)),
                ('coursereqdet', models.TextField(blank=True)),
                ('coursecover', models.CharField(blank=True, max_length=255)),
                ('courseinfo1', models.TextField(blank=True)),
                ('courseinfo2', models.TextField(blank=True)),
                ('courseinfo3', models.TextField(blank=True)),
                ('courseinfo4', models.TextField(blank=True)),
                ('courseinfo5', models.TextField(blank=True)),
                ('courseinfo6', models.TextField(blank=True)),
                ('courseinfo7', models.TextField(blank=True)),
                ('courseinfo8', models.TextField(blank=True)),
                ('courseinfo9', models.TextField(blank=True)),
                ('courseinfo10', models.TextField(blank=True)),
                ('courseinfo11', models.TextField(blank=True)),
                ('courseinfo12', models.TextField(blank=True)),
                ('courseinfo13', models.TextField(blank=True)),
                ('courseinfo14', models.TextField(blank=True)),
                ('coursestart', models.CharField(max_length=255, null=True)),
                ('contactdetails', models.TextField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Python Course JPN',
            },
        ),
    ]
